# Generated by Django 6.0.7 on 2026-07-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptify_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
